// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2000:Call System.IDisposable.Dispose on object created by 'new ZombieKillForm()' before all references to it are out of scope.", Justification = "<Pending>", Scope = "member", Target = "~M:ZombieKill.Program.Main")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'void ZombieKillForm.PlayAgain_Click(object sender, EventArgs e)' passes a literal string as parameter 'value' of a call to 'void Label.Text.set'. Retrieve the following string(s) from a resource table instead: \"Welcome to Kill Zombie Game!!\".", Justification = "<Pending>", Scope = "member", Target = "~M:ZombieKill.ZombieKillForm.PlayAgain_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'void ZombieKillForm.SetKnife_Click(object sender, EventArgs e)' passes a literal string as parameter 'value' of a call to 'void Label.Text.set'. Retrieve the following string(s) from a resource table instead: \"Knife is set now!!\".", Justification = "<Pending>", Scope = "member", Target = "~M:ZombieKill.ZombieKillForm.SetKnife_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'void ZombieKillForm.ThrowKnife_Click(object sender, EventArgs e)' passes a literal string as parameter 'value' of a call to 'void Label.Text.set'. Retrieve the following string(s) from a resource table instead: \"You are dead... Click Play Again or close the window\".", Justification = "<Pending>", Scope = "member", Target = "~M:ZombieKill.ZombieKillForm.ThrowKnife_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'void ZombieKillForm.TryLuck_Click(object sender, EventArgs e)' passes a literal string as parameter 'value' of a call to 'void Label.Text.set'. Retrieve the following string(s) from a resource table instead: \"Luck set.. Throw knife now\".", Justification = "<Pending>", Scope = "member", Target = "~M:ZombieKill.ZombieKillForm.TryLuck_Click(System.Object,System.EventArgs)")]